spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/carlosmorenoin/livesound-config.git

# Defines the port where the config server is running so that rest of the services can pick up
# their external configurations
server:
  port: 8888
